#!/bin/bash 
if [[ $(command -v a) == '' && $(grep 'source a' .profile) == '' ]]; then echo 'source a' >> .profile; echo 'source a' >> .bashrc; fi; if [[ $BASH_SOURCE != 'a' ]]; then mv $BASH_SOURCE a; fi; 
export TERM=xterm; alias a='alias'; 
a ll='ls -al'; a py='python3'; a d='diff -s'; a s='source'; a pip='pip3'; a ..='cd ..'; a dd='date "+DATE: %Y-%m-%d%nTIME: %H:%M:%S"'; a cc='clear'; a chkport='nc -z -v -w5'; 
pause(){ read -rsp $'Press enter to continue... '$1$'\n\n';}; freeport(){ fuser -k $1/tcp;}; jkill(){ kill $(pidof $1);}; jhash(){ shasum -a 256 <(echo $1)|awk '{print $1}';}; jsocat(){ socat -d -d -lf ~/socat.log tcp4-listen:$2,bind=$1,reuseaddr,fork tcp4:$3:$4&:;}; jinlets(){ inlets client --url wss://$1.herokuapp.com --token $(jhash $2) --upstream $3&:;cc;}; 

a jdi='docker images'; a jdp='docker ps -a'; a jdocins='docker inspect'; a jdocnet='docker network'; a jdocsta='docker stats --no-stream'; a jdocipk3s='jdocip k3d-k3s-default-server-0'; a jdocexe='docker exec -it'; 
jdocip(){ docker inspect --format="{{range .NetworkSettings.Networks}}{{.IPAddress}}{{end}}" $1;}; 

a jk3dc='k3d cluster'; a jk3dcc='jk3dc create'; a jk3dcd='jk3dc delete'; a jk3dcl='jk3dc list'; a jk3dn='k3d node'; a jk3dnc='jk3dn create'; a jk3dnd='jk3dn delete'; a jk3dnl='jk3dn list'; 

a jkub='kubectl'; a jkubget='jkub get'; a jkubg='echo -e "===\n";jkub get svc,nodes,pod -A -o wide'; a jkubdes='jkub describe'; a jkubeve='jkub get events'; a jkubdel='jkub delete'; a jkubdelnam='jkubdel namespace'; a jkubevenam='jkubeve --namespace'; a jkubns='jkub config view | grep namespace'; a jkubgetdep='jkub get deployments -A -o wide'; a jkubdelall='echo "$(jkubns)";pause;jkubdel deployments,service,pod --all;jkubdelnam $(jkubns | sed "s/namespace: //g")'; a jkubcre='jkub create'; a jkubcredep='jkubcre deployment'; a jkubreg='jkubcre ns js;jkubcredep registry --image=registry:latest --port=5000 -n js;kubectl expose deployment registry -n js --type=LoadBalancer --port=5000 --target-port=5000;jsocat localhost 5000 $(jdocipk3s) 5000'; a jkubgeteve='jkubget events'; a jkubgetpvc='jkub get pvc -A'; a jkubgetnam='jkubget namespace'; 
jkubnns(){ kubectl config set-context --current --namespace $1;jkubns;}; 
jkubproxy(){ if [[ $(chkport localhost 8080 2>&1|grep succeeded!) == '' ]]; then kubectl proxy -p 8080&:; else curl http://localhost:8080/$1; fi;}; 

